export interface PageDefinition {
  id: string;
  label: string;
}

export const pagesList: PageDefinition[] = [
  { id: "dashboard", label: "Dashboard" },
  { id: "leads", label: "Leads" },
  { id: "contacts", label: "Contatos" },
  { id: "accounts", label: "Contas" },
  { id: "opportunities", label: "Oportunidades" },
  { id: "deals", label: "Negócios" },
  { id: "forecasts", label: "Previsões" },
  { id: "proposals", label: "Propostas" },
  { id: "contracts", label: "Contratos" },
  { id: "billing", label: "Faturamento" },
  { id: "products", label: "Produtos" },
  { id: "pricing-tables", label: "Tabelas de preço" },
  { id: "campaigns", label: "Campanhas" },
  { id: "email-marketing", label: "E-mail" },
  { id: "landing-pages", label: "Landing pages" },
  { id: "forms", label: "Formulários" },
  { id: "social", label: "Social" },
  { id: "seo", label: "SEO" },
  { id: "ads", label: "Ads" },
  { id: "marketing-library", label: "Biblioteca" },
  { id: "tickets", label: "Tickets" },
  { id: "knowledge-base", label: "Base de conhecimento" },
  { id: "chat", label: "Chat" },
  { id: "slas", label: "SLAs" },
  { id: "cases", label: "Casos" },
  { id: "portal", label: "Portal" },
  { id: "support-feedback", label: "Feedback" },
  { id: "inbox", label: "Inbox" },
  { id: "communication-emails", label: "E-mails" },
  { id: "calls", label: "Chamadas" },
  { id: "meetings", label: "Reuniões" },
  { id: "sms", label: "SMS" },
  { id: "whatsapp", label: "WhatsApp" },
  { id: "executive-dashboard", label: "Dashboard executivo" },
  { id: "cohorts", label: "Cohorts" },
  { id: "analytics-pipeline", label: "Pipeline" },
  { id: "roi", label: "ROI" },
  { id: "maps", label: "Mapas" },
  { id: "analytics-forecasts", label: "Previsões" },
  { id: "workflows", label: "Workflows" },
  { id: "sequences", label: "Sequências" },
  { id: "playbooks", label: "Playbooks" },
  { id: "triggers", label: "Triggers" },
  { id: "logs", label: "Logs" },
  { id: "connectors", label: "Conectores" },
  { id: "members", label: "Membros" },
  { id: "permissions", label: "Permissões" },
  { id: "goals", label: "Metas" },
  { id: "commissions", label: "Comissões" },
  { id: "territories", label: "Territórios" },
  { id: "leaderboards", label: "Leaderboards" },
  { id: "hub", label: "Hub" },
  { id: "marketplace", label: "Marketplace" },
  { id: "api-console", label: "API console" },
  { id: "webhooks", label: "Webhooks" },
  { id: "import-export", label: "Import/Export" },
  { id: "copilot", label: "Copilot" },
  { id: "insights", label: "Insights" },
  { id: "voice-commands", label: "Comandos de voz" },
  { id: "ai-forecast", label: "Forecast" },
  { id: "action-plan", label: "Plano de ação" },
  { id: "laboratory", label: "Laboratório" },
  { id: "settings", label: "Configurações" },
  { id: "branding", label: "Branding" },
  { id: "security", label: "Segurança" },
  { id: "audit-log", label: "Audit log" },
  { id: "onboarding", label: "Onboarding" },
  { id: "community", label: "Comunidade" },
];
