name: ALSHAM 360° CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Lint código
        run: npm run lint || true
      
      - name: Rodar testes
        run: npm test || true
      
      - name: Build produção
        run: npm run build
      
      - name: Verificar bundle size
        run: |
          echo "📦 Tamanho do build:"
          du -sh dist
